### ISSUE TITLE
hey

### ISSUE THREAD

**Issue by halukmy** [died/TensorflowObjectDetectionCompare#1]
thanks for tensorflowsharp :)

**Comment by died** [comment]
you are welcome :)

**Comment by halukmy** [comment]
can you start learn tensorflowsharp series ? :)

im planningt o create smart city iot apps with ai and tensorflowsharp but i dont know how 

i will be so happy about your shares 👍

**Comment by died** [comment]
@halukmy I will try it if I can get more free time lol.

**Comment by halukmy** [comment]
verryyy coooool m8 :))

got mail, fb or linkedin?

we are ai brothers after todayyyyyy

**Comment by died** [comment]
you can check my blog, on the left side has a image show my email.

**Comment by halukmy** [comment]
i always been there :)

im so exciting about start ai with tensorflowsharp with you buddy :)

i like your style and your quote on your blog a hour ago

lets make train the fukin whole machines 💃

**Comment by halukmy** [comment]
lol i cant find

**Comment by died** [comment]
![here](http://farm5.static.flickr.com/4131/5040764305_8d3ff14947_m.jpg) <-- I don't wanna type it out bcz it will be collect by spam mail lol.

**Comment by halukmy** [comment]
looooooooooooooooooooooooool
