### ISSUE TITLE
Making a custom object detector

### ISSUE THREAD

**Issue by Amanpradhan** [died/TensorflowObjectDetectionCompare#2]
Hi, so I want to build a custom object detector and integrate it in tensorflow sharp. Can you tell me which model to use and how to train it?

Regards,
Aman

**Comment by died** [comment]
@Amanpradhan I didn't used tensorflowsharp train model before, but I think you can find python code for training model very easy.
You can get and test some model from [tensorflow model zoo](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/detection_model_zoo.md), then looking the sample code for training, after model done, then using tensorflowsharp.
